[package]
name = "vec_map"
version = "0.9.0"
authors = ["Alex Crichton <alex@alexcrichton.com>",
           "Jorge Aparicio <japaricious@gmail.com>",
           "Alexis Beingessner <a.beingessner@gmail.com>",
           "Brian Anderson <>",
           "tbu- <>",
           "Manish Goregaokar <>",
           "Aaron Turon <aturon@mozilla.com>",
           "Adolfo Ochagavía <>",
           "Niko Matsakis <>",
           "Steven Fackler <>",
           "Chase Southwood <csouth3@illinois.edu>",
           "Eduard Burtescu <>",
           "Florian Wilkens <>",
           "Félix Raimundo <>",
           "Tibor Benke <>",
           "Markus Siemens <markus@m-siemens.de>",
           "Josh Branchaud <jbranchaud@gmail.com>",
           "Huon Wilson <dbau.pp@gmail.com>",
           "Corey Farwell <coref@rwell.org>",
           "Aaron Liblong <>",
           "Nick Cameron <nrc@ncameron.org>",
           "Patrick Walton <pcwalton@mimiga.net>",
           "Felix S Klock II <>",
           "Andrew Paseltiner <apaseltiner@gmail.com>",
           "Sean McArthur <sean.monstar@gmail.com>",
           "Vadim Petrochenkov <>",
           "Jonathan Behrens <fintelia@gmail.com>"]

license = "MIT/Apache-2.0"
description = "A simple map based on a vector for small integer keys"
repository = "https://github.com/fintelia/vec-map"
homepage = "https://github.com/fintelia/vec-map"
keywords = ["data-structures", "collections", "vecmap", "vec_map"]
readme = "README.md"

[features]
eders = ["serde", "serde_derive"]

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
